# general settings
name: infer_lolv1
model_type: PGCModel
num_gpu: 2
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: train
    type: LOL_Dataset
    gt_root: "../dataset/LOLv1/our485/high"
    input_root: "../dataset/LOLv1/our485/low"
    input_mode: ~
    concat_with_hiseq: true
    concat_with_coord: true
    concat_with_prior: false
    hiseq_random_cat: false
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_flip: true

    bright_aug: true
    bright_aug_range: [0.5, 1.5]

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    # Please modify accordingly to use your own validation
    # Or comment the val block if do not need validation during training
    name: validation
    type: LOL_Dataset
    gt_root: "../dataset/LSRW/Eval/Nikon/high"
    input_root: "../dataset/LSRW/Eval/Nikon/low"
    concat_with_hiseq: true
    concat_with_coord: true
    concat_with_prior: false
    input_mode: pad
    divide: 32
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]

# network structures
network_unet:
  type: PGCSR3UNet
  in_channel: 14
  out_channel: 3
  inner_channel: 64
  norm_groups: 32
  channel_mults: [1,2,4,8]
  attn_res: [16]
  res_blocks: 2
  dropout: 0.2
  divide: 16
  
network_pencoder:
  type: PEncoder
  in_channel: 4 # 8 + 3
  inner_channel: 64
  norm_groups: 32
  channel_mults: [1,2,4,8]
  res_blocks: 2
  dropout: 0.2
  divide: 16
  
network_colorp:
  type: simpleUNet
  in_channel: 3
  out_channel: 2

network_ddpm:
  type: PGCGaussianDiffusion
  image_size: 128
  channels: 3
  conditional: true
  color_limit: -1
  progressive_list: [192, 160, 128, 96, 64] 
  stride_list: [80, 64, 48, 32, 16] 
ddpm_schedule:
  schedule: "linear"
  n_timestep: 2000
  linear_start: !!float 1e-6
  linear_end: !!float 1e-2

# path
path:
  pretrain_network_g: '../ckpt/lolv1_pgc.pth'
  param_key_g: params
  strict_load_g: False
  pretrain_network_d: ~
  resume_state: ~
  ignore_resume_networks: ['network_identity']

# training settings
train:
  cs_on_shift: true
  vis_train: true
  vis_num: 150
  train_type: ddpm_patch
  t_border: 1000
  input_mode: crop
  optim_g:
    type: Adam
    lr: !!float 1e-4
  optim_d:
    type: Adam
    lr: !!float 2e-3
  optim_component:
    type: Adam
    lr: !!float 2e-3

  scheduler:
    type: MultiStepLR
    milestones: [50000, 75000, 100000, 150000, 200000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

# validation settings
val:
  cal_score: true
  split_log: true
  fix_seed: true
  color_gamma: 1.0
  use_up_v2: true
  progressive_list: [192, 160, 128, 96, 64] 
  stride_list: [80, 64, 48, 32, 16] 
  ddim_eta: !!float 1.0
  ddim_timesteps: 5
  only_save_sr: true
  use_kind_align: false
  cal_all: true
  show_all: true
  val_freq: !!float 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim      
      crop_border: 0
      test_y_channel: false
    lpips:
      type: calculate_lpips_lol

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: false